
services:

  django:
    image: elizarov-backend
    container_name: elizarov-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .environment
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: always


  postgres:
    image: postgres
    container_name: elizarov-backend-postgres
    ports:
      - 5432:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  host:
    name: elizarov
