# Generated by Django 5.1.4 on 2025-05-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArthroplastyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Вид артропластики',
                'verbose_name_plural': 'Виды артропластики',
            },
        ),
        migrations.CreateModel(
            name='OperationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название этапа')),
            ],
            options={
                'verbose_name': 'Этап операции',
                'verbose_name_plural': 'Этапы операций',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('mobile_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина артропластики')),
                ('therapy', models.TextField(blank=True, verbose_name='Полученное лечение')),
                ('form_pjl', models.CharField(blank=True, max_length=255, verbose_name='Вид PJL')),
                ('local_status', models.CharField(blank=True, max_length=255, verbose_name='Локальный статус')),
                ('thigh_defect', models.CharField(blank=True, max_length=255, verbose_name='Дефект бедра по AORI')),
                ('shin_defect', models.CharField(blank=True, max_length=255, verbose_name='Дефект голени по AORI')),
                ('therapy_option', models.CharField(blank=True, max_length=255, verbose_name='Вариант лечения')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.arthroplastyform', verbose_name='Вид артропластики')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Лечения',
            },
        ),
        migrations.CreateModel(
            name='SurgicalIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('wound_character', models.CharField(blank=True, max_length=255, verbose_name='Характер раны')),
                ('drainage', models.CharField(blank=True, max_length=255, verbose_name='Дренирование')),
                ('complications', models.TextField(blank=True, null=True, verbose_name='Осложнения')),
                ('operation_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.operationstage', verbose_name='Этап операции')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment', verbose_name='Лечение')),
            ],
            options={
                'verbose_name': 'Оперативное вмешательство',
                'verbose_name_plural': 'Оперативные вмешательства',
            },
        ),
        migrations.CreateModel(
            name='TreatmentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=255, verbose_name='Исход')),
                ('recurrence', models.BooleanField(verbose_name='Рецидив')),
                ('follow_up_period', models.IntegerField(verbose_name='Период наблюдения (мес)')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment', verbose_name='Лечение')),
            ],
            options={
                'verbose_name': 'Исход лечения',
                'verbose_name_plural': 'Исходы лечения',
            },
        ),
    ]
