# Generated by Django 5.1.4 on 2025-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentoutcome',
            name='follow_up_period',
        ),
        migrations.RemoveField(
            model_name='treatmentoutcome',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='treatmentoutcome',
            name='artodesis',
            field=models.TextField(default=1, verbose_name='В случаях артодеза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentoutcome',
            name='re_audit',
            field=models.TextField(default=1, verbose_name='Повторная ревизия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentoutcome',
            name='result',
            field=models.TextField(default=1, max_length=255, verbose_name='Реузльтат лечения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatmentoutcome',
            name='outcome',
            field=models.TextField(),
        ),
    ]
