# Generated by Django 5.1.4 on 2025-05-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_remove_treatmentoutcome_follow_up_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KAK', models.CharField(blank=True, max_length=255, verbose_name='КАК')),
                ('VKAK', models.CharField(blank=True, max_length=255, verbose_name='ВКАК')),
                ('urine_test', models.CharField(blank=True, max_length=255, verbose_name='Анализ мочи')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='ComorbidPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(default=False, verbose_name='Ожирение')),
                ('diabetes_mellitus', models.BooleanField(default=False, verbose_name='Сахарный диабет')),
                ('hepatitis', models.BooleanField(default=False, verbose_name='Гепатит')),
                ('hiv', models.BooleanField(default=False, verbose_name='ВИЧ')),
                ('hormonal_treatment', models.BooleanField(default=False, verbose_name='Гормональное лечение')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Microflora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microorganism', models.CharField(choices=[('mrse_mrsa', 'MRSE/MRSA'), ('pseudomonas_aeruginosa', 'Pseudomonas aeruginosa'), ('klebsiella_pneumoniae', 'Klebsiella pneumoniae'), ('acinetobacter_baumanii', 'Acinetobacter baumannii')], max_length=50, verbose_name='Микроорганизм')),
                ('mrse_mrsa', models.BooleanField(default=False)),
                ('pseudomonas_aeruginosa', models.BooleanField(default=False)),
                ('klebsiella_pneumoniae', models.BooleanField(default=False)),
                ('acinetobacter_baumanii', models.BooleanField(default=False)),
                ('treatment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment')),
            ],
        ),
    ]
