# Generated by Django 5.1.4 on 2025-05-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndoprostheticForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Форма эндопротеза',
                'verbose_name_plural': 'Формы эндопротезов',
            },
        ),
        migrations.CreateModel(
            name='EndoprostheticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип эндопротеза',
                'verbose_name_plural': 'Типы эндопротезов',
            },
        ),
        migrations.CreateModel(
            name='EndoprostheticVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Производитель эндопротеза',
                'verbose_name_plural': 'Производители эндопротезов',
            },
        ),
        migrations.CreateModel(
            name='Endoprosthetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=255, verbose_name='Партия')),
                ('date', models.DateField(verbose_name='Дата выпуска')),
                ('stable', models.BooleanField(verbose_name='Стабильность эндопротеза')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.patient', verbose_name='Пациент')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endoprosthetics.endoprostheticform', verbose_name='Вид')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endoprosthetics.endoprosthetictype', verbose_name='Тип')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endoprosthetics.endoprostheticvendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Эндопротез',
                'verbose_name_plural': 'Эндопротезы',
            },
        ),
    ]
